# Generated by Django 4.1.4 on 2022-12-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.IntegerField(null=True),
        ),
    ]
