# Generated by Django 4.1.4 on 2022-12-19 13:12

import accounts.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registration_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts.manager.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_loggined',
        ),
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
