# Generated by Django 4.1.4 on 2022-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
